id: P002899
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:12.128829
source_metadata:
  id: bdr:W1KG22445
  title: འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་སྒྲུབ་ཐབས་སོགས།
  author: ''
  volumes:
    2dfe0d25dc58438ab7a34f267a1bf646:
      image_group_id: I1KG22465
      title: ''
      volume_number: 1
      total_pages: 558
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
