id: IE466DCB8
legacy_id: P002899
ocr_import_info:
  bdrc_scan_id: W1KG22445
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:20:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:13:14.613357+00:00'
last_modified: 2022-08-31 21:13:35.186553
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22445
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22445
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇིགས་བྱེད་དཔའ་བོ་གཅིག་པའི་སྒྲུབ་ཐབས་སོགས།
  author: ཕ་བོང་ཁ་པ་བདེ་ཆེན་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6869757577568328
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I1KG22465:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22465
      total_pages: 558
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22465.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6869757577568328
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
